#!/bin/bash
# run_chatextract_batch.sh

CSV_FILE="papers_1-15.csv"
PROPERTIES=(
    "common formula of materials"
    "shape"
    "common name of structure"
    "space group"
    "international table number"
    "lattice constant a"
    "lattice constant c"
    "Tc from susceptibility measurement"
    "Tc (of this sample) recommended"
    "method of Hc1 derivation"
    "Hc1 at 0 K for single crystal for H //ab-plane"
    "Hc1 at 0 K for single crystal for H //c-axis"
    "method of Hc2 derivation"
    "Hc2 at 0 K for single crystal for H //ab-plane"
    "Hc2 at 0 K for single crystal for H //c-axis"
    "method of dHc2/dT derivation"
    "-slope in Hc2 vs T at Tc for single crystal for H //ab-plane"
    "-slope in Hc2 vs T at Tc for single crystal for H //c-axis"
    "method of COHERE derivation"
    "coherence length at 0 K for single crystal for H //ab-plane"
    "coherence length at 0 K for single crystal for H ⊥ab-plane"
    "method of PENET derivation"
    "penetration depth at 0 K for single crystal for H //ab-plane"
    "penetration depth at 0 K for single crystal for H⊥ab-plane"
    "energy gap at 0 K , delta(0)"
    "normarized energy gap at 0 K , 2delta(0)/kTc"
    "method of measuring energy gap"
    "coefficient of electronic specific heat"
    "Debye temperature"
    "method for derivation of Debye temperature"
    "resistivity at 4.2 K for single crystal for J//ab-plane"
    "resistivity at 4.2 K for single crystal for J//c-axis"
    "resistivity at RT for single crystal for J//ab-plane"
    "resistivity at RT for single crystal for J//c-axis"
    "lattice constant b"
    "temperature dependence of LATA"
    "temperature dependence of LATB"
    "temperature dependence of LATC"
    "transition temperature (mid point)"
    "transition width for resistive transition"
    "volume fraction of Meissner effect(%)"
    "Hc1 at given temperature for single crystal H//ab-plane"
    "Hc1 at given temperature for single crystal H//c-axis"
    "measuring temperature"
    "coherence length at 0 K for poly crystal"
    "penetration depth at 0 K for poly crystal"
    "resistivity at normal-T for single crystal for J//ab-plane"
    "carrier density at 300 K"
    "raw materials"
    "*crystal structure, symmetry"
    "*method of analysis for structure"
    "tc measurement method"
    "maximum pressure applied"
    "Hc2 at 0 K for poly crystal"
    "Hc2 at given temperature for single crystal H//ab-plane"
    "thermal conductivity at 300 K"
    "thermopower at 300 K for parallel to ab-plane"
    "*preparation method"
    "transition temperature (R = 100%)"
    "Jc at 4.2 K, H = 0 T"
    "resistivity at 4.2 K for poly crystal"
    "Hall coefficient at 300 K for single, H//c-axis"
    "Hall coefficient at 300 K for single, H//ab-plane"
    "thermal conductivity at 300 K for heat flow//c-axis"
    "thermal conductivity at 300 K for heat flow//ab-plane"
    "Neel temperature"
    "transition temperature (R = 0)"
    "Hc1 at given temperature for poly crystal"
    "Hc2 at given temperature for poly crystal"
    "resistivity at normal-T for poly crystal"
    "resistivity at RT for poly crystal"
    "Hall coefficient at 300 K"
    "Hall coefficient for single, H//c-axis"
    "Hc2 at given temperature for single crystal H//c-axis"
    "normal temperature"
    "substrate"
    "temperature independent term in susceptibility"
    "Curie constant"
    "magnetic moment per formula"
    "Curie temperature"
    "density (gcm-3)"
    "lowest temperature for measurement (not superconducting)"
    "Hc1 at 0 K for poly crystal"
    "alpha in Tc = A * M^(-alpha), isotope effect"
    "isotope element"
    "exchange ratio of isotope(%)"
    "DTC = Tc - Tc0 for isotope element"
    "pressure dependence of LATA"
    "pressure dependence of LATB"
    "pressure dependence of LATC"
    "resistivity at 77 K for poly crystal"
    "resistivity at 77 K for single crystal for J//ab-plane"
    "resistivity at 77 K for single crystal for J//c-axis"
    "resistivity at normal-T for single crystal for J//c-axis"
    "specific heat jump at Tc (delta-C)"
    "thermopower at 300 K"
    "Jc at T = 77 K, H = 0 T"
    "magnetic field for Hall effect"
    "target material"
)

for property in "${PROPERTIES[@]}"; do
    echo "=================================================="
    echo "Extracting: $property"
    echo "=================================================="
    python chatextract.py "$CSV_FILE" "$property"
done

echo "All extractions complete!"